function qdot_q_j = M_qdot_dq_fcn(q1,q2,q3,q4,w1,w2,w3)
%M_QDOT_DQ_FCN
%    QDOT_Q_J = M_QDOT_DQ_FCN(Q1,Q2,Q3,Q4,W1,W2,W3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-Feb-2020 12:55:17

t2 = w1./2.0;
t3 = w2./2.0;
t4 = w3./2.0;
t5 = -t2;
t6 = -t3;
t7 = -t4;
qdot_q_j = reshape([0.0,t2,t3,t4,t5,0.0,t7,t3,t6,t4,0.0,t5,t7,t6,t2,0.0],[4,4]);
