function qdot_w_j = M_qdot_dw_fcn(w1,w2,w3,q1,q2,q3,q4)
%M_QDOT_DW_FCN
%    QDOT_W_J = M_QDOT_DW_FCN(W1,W2,W3,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-Feb-2020 12:55:17

t2 = q1./2.0;
t3 = q2./2.0;
t4 = q3./2.0;
t5 = q4./2.0;
t6 = -t3;
t7 = -t4;
t8 = -t5;
qdot_w_j = reshape([t6,t2,t5,t7,t7,t8,t2,t3,t8,t4,t6,t2],[4,3]);
