function rddot_q_j = M_rddot_dq_fcn(q1,q2,q3,q4,a1,a2,a3)
%M_RDDOT_DQ_FCN
%    RDDOT_Q_J = M_RDDOT_DQ_FCN(Q1,Q2,Q3,Q4,A1,A2,A3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    26-Feb-2020 17:00:02

t2 = a1.*q1.*2.0;
t3 = a1.*q2.*2.0;
t4 = a2.*q1.*2.0;
t5 = a1.*q3.*2.0;
t6 = a2.*q2.*2.0;
t7 = a3.*q1.*2.0;
t8 = a1.*q4.*2.0;
t9 = a2.*q3.*2.0;
t10 = a3.*q2.*2.0;
t11 = a2.*q4.*2.0;
t12 = a3.*q3.*2.0;
t13 = a3.*q4.*2.0;
t14 = -t5;
t15 = -t10;
t16 = -t11;
t17 = t3+t9+t13;
t18 = t6+t7+t14;
t19 = t4+t8+t15;
t20 = t2+t12+t16;
rddot_q_j = reshape([t20,t19,t18,t17,t5-t6-t7,t19,t18,t17,-t2+t11-t12,-t4-t8+t10,t20,t17],[3,4]);
