function rddot_w_j = M_rddot_dw_fcn(w1,w2,w3)
%M_RDDOT_DW_FCN
%    RDDOT_W_J = M_RDDOT_DW_FCN(W1,W2,W3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    26-Feb-2020 17:00:03

rddot_w_j = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
