function rddot_q_j = M_rddot_dq_fcn(q1,q2,q3,q4,a1,a2,a3,r1,r2,r3,w1,w2,w3)
%M_RDDOT_DQ_FCN
%    RDDOT_Q_J = M_RDDOT_DQ_FCN(Q1,Q2,Q3,Q4,A1,A2,A3,R1,R2,R3,W1,W2,W3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-Feb-2020 12:24:19

t2 = r1.*w2;
t3 = r2.*w1;
t4 = r1.*w3;
t5 = r3.*w1;
t6 = r2.*w3;
t7 = r3.*w2;
t8 = -a3;
t9 = -t3;
t10 = -t5;
t11 = -t7;
t12 = t2+t9;
t13 = t4+t10;
t14 = t6+t11;
t15 = t12.*w1;
t16 = t12.*w2;
t17 = t13.*w1;
t18 = t13.*w3;
t19 = t14.*w2;
t20 = t14.*w3;
t21 = -t15;
t22 = a1+t16+t18;
t28 = t8+t17+t19;
t23 = a2+t20+t21;
t24 = q1.*t22.*2.0;
t25 = q2.*t22.*2.0;
t26 = q3.*t22.*2.0;
t27 = q4.*t22.*2.0;
t35 = q1.*t28.*2.0;
t36 = q2.*t28.*2.0;
t37 = q3.*t28.*2.0;
t38 = q4.*t28.*2.0;
t29 = -t26;
t30 = q1.*t23.*2.0;
t31 = q2.*t23.*2.0;
t32 = q3.*t23.*2.0;
t33 = q4.*t23.*2.0;
t39 = -t35;
t40 = -t37;
t41 = -t38;
t34 = -t33;
t42 = t27+t30+t36;
t43 = t25+t32+t41;
t44 = t29+t31+t39;
t45 = t24+t34+t40;
rddot_q_j = reshape([t45,t42,t44,t43,t26-t31+t35,t42,t44,t43,-t24+t33+t37,-t42,t45,t43],[3,4]);
