function norm_fcn_j = norm_fcn_j(v1,v2,v3)
%NORM_FCN_J
%    NORM_FCN_J = NORM_FCN_J(V1,V2,V3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    06-Mar-2020 15:54:44

t2 = abs(v1);
t3 = abs(v2);
t4 = abs(v3);
t5 = t2.^2;
t6 = t3.^2;
t7 = t4.^2;
t8 = t5+t6+t7;
t9 = 1.0./sqrt(t8);
norm_fcn_j = [t2.*t9.*sign(v1),t3.*t9.*sign(v2),t4.*t9.*sign(v3)];
