function dfdq = poison_eq_jacob(q1,q2,q3,q4,v1,v2,v3)
%POISON_EQ_JACOB
%    DFDQ = POISON_EQ_JACOB(Q1,Q2,Q3,Q4,V1,V2,V3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    07-Feb-2020 17:42:36

t2 = v1./2.0;
t3 = v2./2.0;
t4 = v3./2.0;
t5 = -t2;
t6 = -t3;
t7 = -t4;
dfdq = reshape([0.0,t2,t3,t4,t5,0.0,t7,t3,t6,t4,0.0,t5,t7,t6,t2,0.0],[4,4]);
