function dfdq = quat_dual_rot_jacob(q1,q2,q3,q4,v1,v2,v3)
%QUAT_DUAL_ROT_JACOB
%    DFDQ = QUAT_DUAL_ROT_JACOB(Q1,Q2,Q3,Q4,V1,V2,V3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    10-Feb-2020 18:46:32

t2 = q1.*v1.*2.0;
t3 = q1.*v2.*2.0;
t4 = q2.*v1.*2.0;
t5 = q1.*v3.*2.0;
t6 = q2.*v2.*2.0;
t7 = q3.*v1.*2.0;
t8 = q2.*v3.*2.0;
t9 = q3.*v2.*2.0;
t10 = q4.*v1.*2.0;
t11 = q3.*v3.*2.0;
t12 = q4.*v2.*2.0;
t13 = q4.*v3.*2.0;
dfdq = reshape([-t11+t12,t8-t10,-t6+t7,t9+t13,t5+t7-q2.*v2.*4.0,-t3+t10-q2.*v3.*4.0,-t5+t6-q3.*v1.*4.0,t4+t13,t2+t12-q3.*v3.*4.0,t3+t8-q4.*v1.*4.0,-t2+t11-q4.*v2.*4.0,t4+t9],[3,4]);
