function quat_rot_fcn_j = quat_rot_fcn_j(q1,q2,q3,q4,v1,v2,v3)
%QUAT_ROT_FCN_J
%    QUAT_ROT_FCN_J = QUAT_ROT_FCN_J(Q1,Q2,Q3,Q4,V1,V2,V3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    06-Mar-2020 15:39:10

t2 = q1.*v1.*2.0;
t3 = q1.*v2.*2.0;
t4 = q2.*v1.*2.0;
t5 = q1.*v3.*2.0;
t6 = q2.*v2.*2.0;
t7 = q3.*v1.*2.0;
t8 = q2.*v3.*2.0;
t9 = q3.*v2.*2.0;
t10 = q4.*v1.*2.0;
t11 = q3.*v3.*2.0;
t12 = q4.*v2.*2.0;
t13 = q4.*v3.*2.0;
t14 = -t7;
t15 = -t8;
t16 = -t12;
t17 = t4+t9+t13;
t18 = t5+t6+t14;
t19 = t3+t10+t15;
t20 = t2+t11+t16;
quat_rot_fcn_j = reshape([t20,t19,t18,t17,-t5-t6+t7,t19,t18,t17,-t2-t11+t12,-t3+t8-t10,t20,t17],[3,4]);
