function imu_a_q_j = Z_aimu_dq_fcn(q1,q2,q3,q4,a1,a2,a3,g1,g2,g3)
%Z_AIMU_DQ_FCN
%    IMU_A_Q_J = Z_AIMU_DQ_FCN(Q1,Q2,Q3,Q4,A1,A2,A3,G1,G2,G3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-Feb-2020 16:05:34

t2 = -g1;
t3 = -g2;
t4 = -g3;
t5 = a1+t2;
t6 = a2+t3;
t7 = a3+t4;
t8 = q1.*t5.*2.0;
t9 = q2.*t5.*2.0;
t10 = q1.*t6.*2.0;
t11 = q3.*t5.*2.0;
t12 = q2.*t6.*2.0;
t13 = q4.*t5.*2.0;
t14 = q1.*t7.*2.0;
t15 = q3.*t6.*2.0;
t16 = q2.*t7.*2.0;
t17 = q4.*t6.*2.0;
t18 = q3.*t7.*2.0;
t19 = q4.*t7.*2.0;
t20 = -t12;
t21 = -t13;
t22 = -t18;
t23 = t9+t15+t19;
t24 = t11+t14+t20;
t25 = t10+t16+t21;
t26 = t8+t17+t22;
imu_a_q_j = reshape([t26,t25,t24,t23,t24,-t10+t13-t16,-t11+t12-t14,t23,t26,t25,-t8-t17+t18,t23],[3,4]);
