function imu_a_w_j = Z_aimu_dw_fcn(w1,w2,w3)
%Z_AIMU_DW_FCN
%    IMU_A_W_J = Z_AIMU_DW_FCN(W1,W2,W3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    06-Mar-2020 14:39:42

imu_a_w_j = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
