function imu_a_w_j = Z_aimu_dw_fcn(w1,w2,w3,dr1,dr2,dr3)
%Z_AIMU_DW_FCN
%    IMU_A_W_J = Z_AIMU_DW_FCN(W1,W2,W3,DR1,DR2,DR3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-Feb-2020 16:05:34

t2 = dr1.*w1;
t3 = dr2.*w2;
t4 = dr3.*w3;
imu_a_w_j = reshape([t3+t4,dr1.*w2-dr2.*w1.*2.0,dr1.*w3-dr3.*w1.*2.0,dr1.*w2.*-2.0+dr2.*w1,t2+t4,dr2.*w3-dr3.*w2.*2.0,dr1.*w3.*-2.0+dr3.*w1,dr2.*w3.*-2.0+dr3.*w2,t2+t3],[3,3]);
