function imu_a_a_j = Z_aimu_da_fcn(a1,a2,a3,q1,q2,q3,q4)
%Z_AIMU_DA_FCN
%    IMU_A_A_J = Z_AIMU_DA_FCN(A1,A2,A3,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-Feb-2020 16:05:34

t2 = q1.^2;
t3 = q2.^2;
t4 = q3.^2;
t5 = q4.^2;
t6 = q1.*q2.*2.0;
t7 = q1.*q3.*2.0;
t8 = q1.*q4.*2.0;
t9 = q2.*q3.*2.0;
t10 = q2.*q4.*2.0;
t11 = q3.*q4.*2.0;
t12 = -t3;
t13 = -t4;
t14 = -t5;
imu_a_a_j = reshape([t2+t3+t13+t14,-t8+t9,t7+t10,t8+t9,t2+t4+t12+t14,-t6+t11,-t7+t10,t6+t11,t2+t5+t12+t13],[3,3]);
