function rgnns_q_j = Z_rgnns_dq_fcn(q1,q2,q3,q4,r1,r2,r3)
%Z_RGNNS_DQ_FCN
%    RGNNS_Q_J = Z_RGNNS_DQ_FCN(Q1,Q2,Q3,Q4,R1,R2,R3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    04-Mar-2020 18:28:41

t2 = q1.*r1.*2.0;
t3 = q1.*r2.*2.0;
t4 = q2.*r1.*2.0;
t5 = q1.*r3.*2.0;
t6 = q2.*r2.*2.0;
t7 = q3.*r1.*2.0;
t8 = q2.*r3.*2.0;
t9 = q3.*r2.*2.0;
t10 = q4.*r1.*2.0;
t11 = q3.*r3.*2.0;
t12 = q4.*r2.*2.0;
t13 = q4.*r3.*2.0;
t14 = -t7;
t15 = -t8;
t16 = -t12;
t17 = t4+t9+t13;
t18 = t5+t6+t14;
t19 = t3+t10+t15;
t20 = t2+t11+t16;
rgnns_q_j = reshape([t20,t19,t18,t17,-t5-t6+t7,t19,t18,t17,-t2-t11+t12,-t3+t8-t10,t20,t17],[3,4]);
