function rgnns_q_j = Z_rgnns_dq_fcn(q1,q2,q3,q4,dr1,dr2,dr3)
%Z_RGNNS_DQ_FCN
%    RGNNS_Q_J = Z_RGNNS_DQ_FCN(Q1,Q2,Q3,Q4,DR1,DR2,DR3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-Feb-2020 14:14:58

t2 = dr1.*q1.*2.0;
t3 = dr1.*q2.*2.0;
t4 = dr2.*q1.*2.0;
t5 = dr1.*q3.*2.0;
t6 = dr2.*q2.*2.0;
t7 = dr3.*q1.*2.0;
t8 = dr1.*q4.*2.0;
t9 = dr2.*q3.*2.0;
t10 = dr3.*q2.*2.0;
t11 = dr2.*q4.*2.0;
t12 = dr3.*q3.*2.0;
t13 = dr3.*q4.*2.0;
t14 = -t5;
t15 = -t10;
t16 = -t11;
t17 = t3+t9+t13;
t18 = t6+t7+t14;
t19 = t4+t8+t15;
t20 = t2+t12+t16;
rgnns_q_j = reshape([t20,t19,t18,t17,t5-t6-t7,t19,t18,t17,-t2+t11-t12,-t4-t8+t10,t20,t17],[3,4]);
