function vgnns_v_j = Z_vgnns_ad_dv_fcn(v1,v2,v3,q1,q2,q3,q4)
%Z_VGNNS_AD_DV_FCN
%    VGNNS_V_J = Z_VGNNS_AD_DV_FCN(V1,V2,V3,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-Feb-2020 15:33:32

t2 = abs(v1);
t3 = abs(v2);
t4 = abs(v3);
t5 = sign(v1);
t6 = sign(v2);
t7 = sign(v3);
t8 = q1.^2;
t9 = q2.^2;
t10 = q3.^2;
t11 = q4.^2;
t12 = t2.^2;
t13 = t3.^2;
t14 = t4.^2;
t15 = t12+t13+t14;
t16 = 1.0./sqrt(t15);
vgnns_v_j = reshape([t2.*t5.*t8.*t16+t2.*t5.*t9.*t16-t2.*t5.*t10.*t16-t2.*t5.*t11.*t16,q1.*q4.*t2.*t5.*t16.*2.0+q2.*q3.*t2.*t5.*t16.*2.0,q1.*q3.*t2.*t5.*t16.*-2.0+q2.*q4.*t2.*t5.*t16.*2.0,t3.*t6.*t8.*t16+t3.*t6.*t9.*t16-t3.*t6.*t10.*t16-t3.*t6.*t11.*t16,q1.*q4.*t3.*t6.*t16.*2.0+q2.*q3.*t3.*t6.*t16.*2.0,q1.*q3.*t3.*t6.*t16.*-2.0+q2.*q4.*t3.*t6.*t16.*2.0,t4.*t7.*t8.*t16+t4.*t7.*t9.*t16-t4.*t7.*t10.*t16-t4.*t7.*t11.*t16,q1.*q4.*t4.*t7.*t16.*2.0+q2.*q3.*t4.*t7.*t16.*2.0,q1.*q3.*t4.*t7.*t16.*-2.0+q2.*q4.*t4.*t7.*t16.*2.0],[3,3]);
