function vgnns_w_j = Z_vgnns_dw_fcn(w1,w2,w3,dr1,dr2,dr3,q1,q2,q3,q4)
%Z_VGNNS_DW_FCN
%    VGNNS_W_J = Z_VGNNS_DW_FCN(W1,W2,W3,DR1,DR2,DR3,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-Feb-2020 14:14:59

t2 = dr1.*q1;
t3 = dr1.*q2;
t4 = dr2.*q1;
t5 = dr1.*q3;
t6 = dr2.*q2;
t7 = dr3.*q1;
t8 = dr1.*q4;
t9 = dr2.*q3;
t10 = dr3.*q2;
t11 = dr2.*q4;
t12 = dr3.*q3;
t13 = dr3.*q4;
t14 = -t6;
t15 = -t7;
t16 = -t10;
t17 = -t11;
t18 = -t12;
t19 = t2+t12;
t20 = t3+t9;
t21 = t4+t8;
t22 = t6+t7;
t23 = t3+t13;
t24 = t9+t13;
t25 = t2+t17;
t26 = t4+t16;
t27 = t5+t14;
t28 = t5+t15;
t29 = t8+t16;
t30 = t11+t18;
vgnns_w_j = reshape([q1.*t24+q4.*t22+q3.*t26+q2.*t30,-q1.*t22-q2.*t26+q4.*t24+q3.*t30,-q2.*t22+q1.*t26-q3.*t24+q4.*t30,-q3.*t19-q4.*t23-q1.*t28-q2.*t29,q2.*t19+q1.*t23-q3.*t29-q4.*t28,-q1.*t19+q2.*t23+q3.*t28-q4.*t29,-q1.*t21+q3.*t20+q2.*t27-q4.*t25,-q2.*t20-q4.*t21+q1.*t25+q3.*t27,q1.*t20+q3.*t21+q2.*t25+q4.*t27],[3,3]);
