function vgnns_w_j = Z_vgnns_dw_fcn(dr1,dr2,dr3,q1,q2,q3,q4)
%Z_VGNNS_DW_FCN
%    VGNNS_W_J = Z_VGNNS_DW_FCN(DR1,DR2,DR3,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    04-Mar-2020 18:28:41

t2 = q2.^2;
t3 = q3.^2;
t4 = q4.^2;
t5 = q1.*q2.*2.0;
t6 = q1.*q3.*2.0;
t7 = q1.*q4.*2.0;
t8 = q2.*q3.*2.0;
t9 = q2.*q4.*2.0;
t10 = q3.*q4.*2.0;
t11 = t2.*2.0;
t12 = t3.*2.0;
t13 = t4.*2.0;
t14 = -t8;
t15 = -t9;
t16 = -t10;
t17 = t5+t10;
t18 = t6+t9;
t19 = t7+t8;
t20 = t5+t16;
t21 = t6+t15;
t22 = t7+t14;
t23 = t11+t12-1.0;
t24 = t11+t13-1.0;
t25 = t12+t13-1.0;
vgnns_w_j = reshape([dr2.*t18+dr3.*t22,-dr2.*t20+dr3.*t24,-dr3.*t17-dr2.*t23,-dr1.*t18-dr3.*t25,dr1.*t20+dr3.*t19,dr1.*t23-dr3.*t21,-dr1.*t22+dr2.*t25,-dr2.*t19-dr1.*t24,dr1.*t17+dr2.*t21],[3,3]);
