function vgnns_q_j = Z_vgnns_dq_fcn(q1,q2,q3,q4,dr1,dr2,dr3,w1,w2,w3)
%Z_VGNNS_DQ_FCN
%    VGNNS_Q_J = Z_VGNNS_DQ_FCN(Q1,Q2,Q3,Q4,DR1,DR2,DR3,W1,W2,W3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-Feb-2020 14:14:58

t2 = dr1.*w2;
t3 = dr2.*w1;
t4 = dr1.*w3;
t5 = dr3.*w1;
t6 = dr2.*w3;
t7 = dr3.*w2;
t8 = -t3;
t9 = -t5;
t10 = -t7;
t11 = t2+t8;
t12 = t4+t9;
t13 = t6+t10;
t14 = q1.*t11.*2.0;
t15 = q2.*t11.*2.0;
t16 = q1.*t12.*2.0;
t17 = q3.*t11.*2.0;
t18 = q2.*t12.*2.0;
t19 = q4.*t11.*2.0;
t20 = q1.*t13.*2.0;
t21 = q3.*t12.*2.0;
t22 = q2.*t13.*2.0;
t23 = q4.*t12.*2.0;
t24 = q3.*t13.*2.0;
t25 = q4.*t13.*2.0;
t26 = -t14;
t27 = -t17;
t28 = -t19;
t29 = -t20;
t30 = -t22;
t31 = -t23;
t32 = -t25;
t33 = t18+t24+t26;
t34 = t15+t16+t32;
t35 = t21+t28+t30;
t36 = t27+t29+t31;
vgnns_q_j = reshape([t36,t34,t33,t35,t14-t18-t24,t34,t33,t35,t17+t20+t23,-t15-t16+t25,t36,t35],[3,4]);
