function vgnns_q_j = Zvq_fcn(q1,q2,q3,q4,v1,v2,v3)
%ZVQ_FCN
%    VGNNS_Q_J = ZVQ_FCN(Q1,Q2,Q3,Q4,V1,V2,V3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-Feb-2020 18:03:54

t2 = abs(v1);
t3 = abs(v2);
t4 = abs(v3);
t5 = t2.^2;
t6 = t3.^2;
t7 = t4.^2;
t8 = t5+t6+t7;
t9 = sqrt(t8);
t10 = q1.*t9.*2.0;
t11 = q2.*t9.*2.0;
t12 = q3.*t9.*2.0;
t13 = q4.*t9.*2.0;
t14 = -t12;
vgnns_q_j = reshape([t10,t13,t14,t11,t12,t13,t14,t11,-t10,-t13,t10,t11],[3,4]);
