function ss = surf_ctrl_pot_test_1(Delta_pss,Pi,Pi_mult,Pis,delta,mu,norm_ps,phi,signX)
%SURF_CTRL_POT_TEST_1
%    SS = SURF_CTRL_POT_TEST_1(DELTA_PSS,PI,PI_MULT,PIS,DELTA,MU,NORM_PS,PHI,SIGNX)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    13-Apr-2021 16:49:30

t2 = abs(delta);
t3 = sin(phi);
t4 = 1.0./t2;
ss = -(t2.*(mu.^2.*(t2+Pi.*Pi_mult)+mu.*t4.*(delta.*cos(phi)+Pi_mult.*Pis.*t2).*2.0+(Delta_pss.*t3.^2.*t4)./(Delta_pss-norm_ps.^2)))./(delta.*signX.*t3);
