function ss = obstacles_potential3(Pi,Pis,k,mu,psi,z1,z2)
%OBSTACLES_POTENTIAL3
%    SS = OBSTACLES_POTENTIAL3(PI,PIS,K,MU,PSI,Z1,Z2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    03-Dec-2020 18:52:24

t2 = cos(psi);
t3 = abs(z1);
t4 = abs(z2);
ss = -(t4.*(Pis+mu.*(Pi+t3+t4).*2.0+(z1.*z2)./t3-(k.*t2.^2.*z2)./(t4.*(k.*z1+1.0))))./(t2.*z2);
