function ss = u_obs_pot_generated(Pi,Pidot,alpha,k,mu,psi,v,z1)
%U_OBS_POT_GENERATED
%    SS = U_OBS_POT_GENERATED(PI,PIDOT,ALPHA,K,MU,PSI,V,Z1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    02-Dec-2020 13:44:53

t2 = cos(psi);
t3 = sin(psi);
t4 = alpha.*t3;
t5 = t4+z1;
ss = ((Pidot+mu.*(Pi+t4.*z1.*2.0+t4.^2+z1.^2).*2.0+t3.*t5.*v.*2.0-(alpha.*k.*t2.^2.*t5.*v.*2.0)./(k.*z1+1.0)).*(-1.0./2.0))./(alpha.*t2.*t5.*v);
