function ss = u_obs_pot_generated4_off(k,mu,psi,z1,z2)
%U_OBS_POT_GENERATED4_OFF
%    SS = U_OBS_POT_GENERATED4_OFF(K,MU,PSI,Z1,Z2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Dec-2020 14:45:54

t2 = cos(psi);
t3 = abs(z1);
t4 = -z2;
t5 = k+t4;
t6 = abs(t5);
ss = (t6.*(mu.*(t3+t6).*2.0+(z1.*z2)./t3+(k.*t2.^2.*t5)./(t6.*(k.*z1+1.0))))./(t2.*t5);
