function ss = u_obs_pot_generated_example(Delta1,Delta2,Delta3,delta,lambda,norm_ps,phi,pss1,pss2,pss3)
%U_OBS_POT_GENERATED_EXAMPLE
%    SS = U_OBS_POT_GENERATED_EXAMPLE(DELTA1,DELTA2,DELTA3,DELTA,LAMBDA,NORM_PS,PHI,PSS1,PSS2,PSS3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    29-Jan-2021 14:18:18

t2 = sin(phi);
t3 = Delta1.*pss1;
t4 = Delta2.*pss2;
t5 = Delta3.*pss3;
ss = -(delta.*lambda.^2+lambda.*cos(phi).*2.0+(t2.^2.*(t3+t4+t5))./(delta.*(t3+t4+t5-norm_ps.^2)))./t2;
