function ss = u_obs_pot_generated4(ev1,ev2,evx1,evx2,k,mu,ndr,psi,r1,r2,rmin,ro1,ro2,z1,z2)
%U_OBS_POT_GENERATED4
%    SS = U_OBS_POT_GENERATED4(EV1,EV2,EVX1,EVX2,K,MU,NDR,PSI,R1,R2,RMIN,RO1,RO2,Z1,Z2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    04-Dec-2020 14:45:02

t2 = cos(psi);
t3 = abs(z1);
t4 = -rmin;
t5 = -ro1;
t6 = -ro2;
t7 = -z2;
t8 = ndr+t4;
t9 = r1+t5;
t10 = r2+t6;
t11 = k+t7;
t12 = abs(t11);
t13 = t8.^2;
t15 = (ev1.*t9)./2.0;
t16 = (ev2.*t10)./2.0;
t14 = 1.0./t12;
t17 = t15+t16-1.0./2.0;
ss = (mu.*(t3+t12-(t13.*t17)./2.0).*2.0-(t13.*(ev1.^2+ev2.^2))./2.0+(z1.*z2)./t3-(t8.*t17.*(ev1.*t9+ev2.*t10))./ndr+(k.*t2.^2.*t11.*t14)./(k.*z1+1.0))./((t13.*(evx1.*t9+evx2.*t10))./2.0+t2.*t11.*t14);
