function ss = u_obs_pot_generated2(Pi_mult,ev1,ev2,evx1,evx2,k,mu,ndr,psi,r1,r2,rmin,ro1,ro2,sinThetaSq,z1,z2)
%U_OBS_POT_GENERATED2
%    SS = U_OBS_POT_GENERATED2(PI_MULT,EV1,EV2,EVX1,EVX2,K,MU,NDR,PSI,R1,R2,RMIN,RO1,RO2,SINTHETASQ,Z1,Z2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    09-Dec-2020 13:56:04

t2 = cos(psi);
t3 = abs(z1);
t4 = 1.0./ndr;
t5 = -rmin;
t6 = -ro1;
t7 = -ro2;
t8 = 1.0./t3;
t9 = ndr+t5;
t10 = r1+t6;
t11 = r2+t7;
t12 = ev1.*t10;
t13 = ev2.*t11;
t14 = t12+t13;
ss = -(mu.^2.*(t3+(Pi_mult.*t9.^2)./2.0)+Pi_mult.*(t4.^2.*t14.^2+sinThetaSq.*t4.*t9)+mu.*(t8.*z1.*z2+Pi_mult.*t4.*t9.*t14).*2.0-(k.*t2.^2.*t8.*z1)./(k.*z1+1.0))./(t2.*t8.*z1+Pi_mult.*t4.*t9.*(evx1.*t10+evx2.*t11));
