function ss = u_obs_pot_generated2_off(k,mu,psi,z1,z2)
%U_OBS_POT_GENERATED2_OFF
%    SS = U_OBS_POT_GENERATED2_OFF(K,MU,PSI,Z1,Z2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    03-Dec-2020 22:35:09

t2 = cos(psi);
t3 = mu.^2;
ss = -(mu.*z2.*2.0+t3.*z1-k.*t2.^2+k.*t3.*z1.^2+k.*mu.*z1.*z2.*2.0)./(t2.*(k.*z1+1.0));
