function ss = u_obs_pot_generated3(Pi,Pis,k,mu,psi,z1,z2)
%U_OBS_POT_GENERATED3
%    SS = U_OBS_POT_GENERATED3(PI,PIS,K,MU,PSI,Z1,Z2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    03-Dec-2020 19:41:32

t2 = cos(psi);
t3 = abs(z1);
t4 = abs(z2);
ss = -(t4.*(Pis+mu.*(Pi+t3+t4).*2.0+(z1.*z2)./t3-(k.*t2.^2.*z2)./(t4.*(k.*z1+1.0))))./(t2.*z2);
